In [ ]:
print("Olá Mundo de novo")

Olá Mundo de novo




##  **Numpy**



In [ ]:
import numpy as np

In [ ]:
# usar a função np.array e passar uma lista para ele
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# montar uma matriz
matriz = np.array([[1,2],[3,4],[5,6]])
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# tamanho da matriz
matriz.shape

(3, 2)

In [ ]:
# com um intervalo de elementos utilizando a função arange(), sendo q inicia no valor zero e o último número nao é incluido no intervalo
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# somar
a.sum()

45

In [ ]:
# valor máximo
print("Valor Máximo", a.max())
# valor mínimo
print("Valor Mínimo", a.min())
# média
print("Média", a.mean())
# somar todos os elementos com o valor 2
print("Soma com o valor acrescentado 2", (a+2))

Valor Máximo 9
Valor Mínimo 0
Média 4.5
Soma com o valor acrescentado 2 [ 2  3  4  5  6  7  8  9 10 11]


# **Pandas**

In [ ]:
import pandas as pd

# há duas estruturas de dados do panda chamados de Series(uma dimensão) e o DataFrame(duas dimensões)
# Os DataFrames, também, podem ser criados a partir de listas, tuplas, dicionários, arquivos externos.

In [ ]:
df = pd.DataFrame(
    {
        "Nome": [
            "Luiz Silva",
            "Maria Luisa da Silva",
            "Roberto Silva",
        ],
        "Idade": [22, 35, 58],
    }
)
df

Nome  Idade
0            Luiz Silva     22
1  Maria Luisa da Silva     35
2         Roberto Silva     58

In [ ]:
# Selecionando uma Série
df["Nome"]

0              Luiz Silva
1    Maria Luisa da Silva
2           Roberto Silva
Name: Nome, dtype: object

In [ ]:
# Criando uma Série
idades = pd.Series([22, 35, 58], index=["Aluno 1", "Aluno 2","Aluno 3"])
idades

Aluno 1    22
Aluno 2    35
Aluno 3    58
dtype: int64

In [22]:
df.shape


(3, 2)

In [21]:
df.columns

Index(['Nome', 'Idade'], dtype='object')

In [25]:
df.dtypes

Nome     object
Idade     int64
dtype: object